[package]
name = "RustDBMS"
version = "0.4.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
chrono = "0.4.38"
serde_json = "1.0.125"
serde = { version = "1.0.208", features = ["derive"] }
fs2 = "0.4.3"
